"use client";

import React, { useState, useEffect } from "react";
import "./DemocracyQuiz.css";

interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export default function DemocracyQuiz() {
  const [questions, setQuestions] = useState<QuizQuestion[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [score, setScore] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  // State for the active question interaction
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);
  const [isQuizComplete, setIsQuizComplete] = useState(false);

  const startQuiz = async () => {
    setIsLoading(true);
    setError(null);
    setQuestions([]);
    setCurrentIdx(0);
    setScore(0);
    setIsAnswered(false);
    setSelectedOption(null);
    setIsQuizComplete(false);

    try {
      const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL ?? "http://localhost:8080";
      const response = await fetch(`${backendUrl}/api/quiz/generate`);
      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Failed to load quiz.");
      }

      setQuestions(data.data);
    } catch (err) {
      console.error(err);
      setError(err instanceof Error ? err.message : "An error occurred.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleOptionClick = (index: number) => {
    if (isAnswered) return; // Prevent double clicking
    
    setSelectedOption(index);
    setIsAnswered(true);

    if (index === questions[currentIdx].correctIndex) {
      setScore((prev) => prev + 1);
    }
  };

  const nextQuestion = () => {
    if (currentIdx < questions.length - 1) {
      setCurrentIdx((prev) => prev + 1);
      setIsAnswered(false);
      setSelectedOption(null);
    } else {
      setIsQuizComplete(true);
    }
  };

  // Render Start Screen
  if (!isLoading && questions.length === 0) {
    return (
      <div className="quiz-container">
        <div className="quiz-card start-screen">
          <span className="quiz-icon">🏆</span>
          <h2>The "Democracy Defender" Quiz</h2>
          <p>Test your knowledge about the Election Commission of India, EVMs, and your voting rights.</p>
          <ul className="quiz-rules">
            <li>5 Unique Questions generated by AI.</li>
            <li>Score 4 or higher to earn the digital badge!</li>
          </ul>
          {error && <div className="error-message">{error}</div>}
          <button className="btn btn-primary start-btn" onClick={startQuiz}>
            Start Quiz
          </button>
        </div>
      </div>
    );
  }

  // Render Loading Screen
  if (isLoading) {
    return (
      <div className="quiz-container">
        <div className="quiz-card loading-screen">
          <div className="spinner"></div>
          <h3>Generating Unique Questions...</h3>
          <p>Our AI is crafting a fresh set of questions just for you.</p>
        </div>
      </div>
    );
  }

  // Render Final Results Screen
  if (isQuizComplete) {
    const isWinner = score >= 4;
    return (
      <div className="quiz-container">
        <div className="quiz-card results-screen">
          <h2>Quiz Complete!</h2>
          <div className="score-display">
            <span className="score-number">{score}</span>
            <span className="score-total">/ {questions.length}</span>
          </div>

          {isWinner ? (
            <div className="badge-container">
              <div className="digital-badge glow">
                <span className="badge-icon">🛡️</span>
                <h4>Democracy Defender</h4>
                <p>Official Badge</p>
              </div>
              <p className="win-message">Congratulations! You have an excellent understanding of your electoral rights.</p>
            </div>
          ) : (
            <div className="keep-learning">
              <span className="keep-learning-icon">📚</span>
              <p>Good effort! Keep learning about the democratic process to earn the badge next time.</p>
            </div>
          )}

          <button className="btn btn-primary start-btn" onClick={startQuiz}>
            Play Again
          </button>
        </div>
      </div>
    );
  }

  // Render Active Question
  const currentQ = questions[currentIdx];

  return (
    <div className="quiz-container">
      <div className="quiz-header">
        <h2>Civic Education Quiz</h2>
        <div className="quiz-progress">
          Question {currentIdx + 1} of {questions.length}
        </div>
      </div>

      <div className="quiz-card question-screen">
        <h3 className="question-text">{currentQ.question}</h3>

        <div className="options-grid">
          {currentQ.options.map((option, index) => {
            let className = "option-btn";
            if (isAnswered) {
              if (index === currentQ.correctIndex) {
                className += " correct";
              } else if (index === selectedOption) {
                className += " wrong";
              }
            }

            return (
              <button 
                key={index} 
                className={className}
                onClick={() => handleOptionClick(index)}
                disabled={isAnswered}
              >
                {option}
              </button>
            );
          })}
        </div>

        {isAnswered && (
          <div className={`explanation-box ${selectedOption === currentQ.correctIndex ? 'success' : 'error'}`}>
            <h4>{selectedOption === currentQ.correctIndex ? '✅ Correct!' : '❌ Incorrect'}</h4>
            <p>{currentQ.explanation}</p>
            <button className="btn btn-primary next-btn" onClick={nextQuestion}>
              {currentIdx < questions.length - 1 ? 'Next Question' : 'View Results'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
